/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/aboutMe.vue')['default']
    Articles: typeof import('./src/components/articles.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    Home: typeof import('./src/components/Home.vue')['default']
    My: typeof import('./src/components/My.vue')['default']
    MyArticles: typeof import('./src/components/myArticles.vue')['default']
    MyLikes: typeof import('./src/components/myLikes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Set: typeof import('./src/components/Set.vue')['default']
    Settings: typeof import('./src/components/settings.vue')['default']
    Write: typeof import('./src/components/Write.vue')['default']
  }
}
