/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomLoginForm: typeof import('./src/components/CustomLoginForm.vue')['default']
    CustomRegisterForm: typeof import('./src/components/CustomRegisterForm.vue')['default']
    CustomResetPasswordForm: typeof import('./src/components/CustomResetPasswordForm.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContain: typeof import('element-plus/es')['ElContain']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElContainr: typeof import('element-plus/es')['ElContainr']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'Sfsfsf.Efd': typeof import('./src/components/sfsfsf.Efd.vue')['default']
    TestComp: typeof import('./src/components/testComp.vue')['default']
  }
}
